from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()

# Title
title = doc.add_heading('Flask 框架简介', level=0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = title.runs[0]
run.font.size = Pt(22)
run.font.bold = True
run.font.color.rgb = RGBColor(0x1A, 0x4C, 0x8C)

# What is Flask
doc.add_heading('一、什么是 Flask', level=1)
p = doc.add_paragraph()
p.add_run('Flask').bold = True
p.add_run(' 是一个用 Python 编写的轻量级 Web 应用框架，由 Armin Ronacher 开发。它基于 ')
p.add_run('Werkzeug').italic = True
p.add_run(' WSGI 工具箱和 ')
p.add_run('Jinja2').italic = True
p.add_run(' 模板引擎构建。')

p2 = doc.add_paragraph('Flask 的设计哲学是保持核心简单且易于扩展，因此被称为 "微框架"。但它并不简陋，借助丰富的扩展库，完全可以支撑大型生产项目。')

# Features
doc.add_heading('二、主要特点', level=1)
features = [
    ('轻量简洁', '核心库非常精简，没有强制要求的工具或库，开发者可按需选择组件。'),
    ('灵活自由', '不强制项目结构，适合从小型脚本到大型应用的各种规模。'),
    ('扩展丰富', '拥有大量官方和社区扩展，如 Flask-SQLAlchemy、Flask-Login、Flask-Mail 等。'),
    ('内置开发服务器', '自带调试服务器，支持自动重载和详细的错误追踪，开发体验极佳。'),
    ('RESTful 友好', '天然支持 RESTful 风格的路由设计，非常适合构建 API 服务。'),
]
for name, desc in features:
    p = doc.add_paragraph(style='List Bullet')
    p.add_run(f'{name}：').bold = True
    p.add_run(desc)

# Quick Start
doc.add_heading('三、快速入门', level=1)
doc.add_paragraph('下面是一个最简 Flask 应用示例：')

code = doc.add_paragraph()
code.alignment = WD_ALIGN_PARAGRAPH.LEFT
code_run = code.add_run("""from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return 'Hello, Flask!'

if __name__ == '__main__':
    app.run(debug=True)""")
code_run.font.name = 'Consolas'
code_run.font.size = Pt(10)

# Add shading to code block (using simple indent as fallback)
for paragraph in doc.paragraphs:
    if 'Hello, Flask!' in paragraph.text:
        paragraph.paragraph_format.left_indent = Inches(0.3)
        paragraph.paragraph_format.space_after = Pt(12)

doc.add_paragraph('保存为 app.py 后运行：')
cmd = doc.add_paragraph()
cmd.alignment = WD_ALIGN_PARAGRAPH.LEFT
cmd_run = cmd.add_run('python app.py')
cmd_run.font.name = 'Consolas'
cmd_run.font.size = Pt(10)
cmd_run.font.bold = True

doc.add_paragraph('然后在浏览器访问 http://127.0.0.1:5000/ 即可看到结果。')

# Scenarios
doc.add_heading('四、适用场景', level=1)
scenarios = [
    '小型网站与快速原型开发',
    '微服务架构中的单个服务',
    'RESTful API 后端服务',
    '机器学习模型的 Web 封装与演示',
    'Python Web 开发的教学与学习',
]
for s in scenarios:
    doc.add_paragraph(s, style='List Number')

# Summary
doc.add_heading('五、总结', level=1)
doc.add_paragraph('Flask 以 "简单但不简陋" 的定位，成为 Python Web 开发领域最受欢迎的框架之一。无论是初学者入门，还是资深开发者构建高并发微服务，Flask 都能提供清晰、优雅的解决方案。')

# Footer
section = doc.sections[0]
footer = section.footer
fp = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
fp.text = "Generated by AI"
fp.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.save('D:/codes/funboost/tests/ai_docs/flask_intro_v2.docx')
print('Word document created successfully!')
